[versions]
kotlin = "2.0.0"
android-tools = "31.13.0"
kotlinpoet = "2.0.0"
xpp3 = "1.1.6"

[libraries]
android-tools-sdk = { group = "com.android.tools", name = "sdk-common", version.ref = "android-tools" }
com-squareup = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
org-ogce = { group = "org.ogce", name = "xpp3", version.ref = "xpp3" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
