[versions]
kotlin = "2.0.0"
guava = "33.5.0-jre"
android-tools = "31.13.0"
kotlinpoet = "2.0.0"
xpp3 = "1.1.6"

[libraries]
google-guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
android-tools-sdk = { group = "com.android.tools", name = "sdk-common", version.ref = "android-tools" }
android-tools = { group = "com.android.tools", name = "common", version.ref = "android-tools" }
com-squareup = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
org-ogce = { group = "org.ogce", name = "xpp3", version.ref = "xpp3" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
